export enum ActivationType {
  GAME = 'GAME',
  DISCORD = 'DISCORD',
  GITHUB = 'GITHUB',
  HACKATHON = 'HACKATHON'
}

export enum ActivationTypePage {
  GAME_ONBOARDING = 'GAME.ONBOARDING',
  GAME_PLAY = 'GAME.PLAY',
  DISCORD = 'DISCORD',
  GITHUB = 'GITHUB',
  HACKATHON = 'HACKATHON',
  LINKS = 'LINKS'
}